name: smartscan_services
description: Shared services for SmartScan
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  isar: ^3.1.0+1
  workmanager: ^0.5.2
  smartscan_models:
    path: ../models
  smartscan_database:
    path: ../database
